### ISSUE TITLE
Don't deploy nexus in Origin

### ISSUE THREAD

**Issue by aopatricio** [siamaksade/openshift-cd-demo#102]
The pod instaled in openshift origin deploy don't starting...

--> Scaling nexus-1 to 1
-- | error: update acceptor rejected nexus-1: pods for rc 'cicd-itonelab/nexus-1' took longer than 600 seconds to become available

Thank you.

Alessandro Patricio

**Comment by siamaksade** [comment]
The Nexus pod uses a init container. You OpenShift might not allow running init-containers. Where did you deploy it?

**Comment by jmferrer** [comment]
Same problem.
This is the "oc logs nexus-2-vftzs":

```
id: cannot find name for user ID 1000440000
2018-10-26 11:46:53,980+0000 INFO  [FelixStartLevel] *SYSTEM org.sonatype.nexus.pax.logging.NexusLogActivator - start
2018-10-26 11:46:56,277+0000 ERROR [FelixStartLevel] *SYSTEM org.apache.karaf.features.internal.service.BootFeaturesInstaller - Error installing boot features
org.osgi.framework.BundleException: The framework has been shutdown.
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2978)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
	at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundle0(BundleIdBasedRegion.java:117)
	at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundleAtLocation(BundleIdBasedRegion.java:97)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installBundle(FeaturesServiceImpl.java:1261)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:739)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by jmferrer** [comment]
My persistent storage is too slow.

Changing spec.strategy.recreateParams.timeoutSeconds from 600 to 1200 in nexus dc fixed the issue.

**Comment by siamaksade** [comment]
The nexus template is updated https://github.com/OpenShiftDemos/nexus/commit/6f55656c8b574d006d45507c2af6a3eafc89a53a
