### ISSUE TITLE
[SOLVED][WORKAROUND] Pipeline fails on 'Deploy DEV' on local 3.4 oc cluster installation

### ISSUE THREAD

**Issue by karstengresch** [siamaksade/openshift-cd-demo#46]
Hi all,

tried to follow the setup as described here and followed Siamak's videos at http://www.sonatype.org/nexus/2017/02/15/cicd-with-openshift/ but had no luck so far.

Setup on latest macOS with oc-cluster wrapper, i.e. startup command is

```
>$ occ show
# Using client for ocp v3.4.1.10
oc cluster up --version v3.4.1.10 --image registry.access.redhat.com/openshift3/ose --public-hostname 127.0.0.1 --routing-suffix apps.127.0.0.1.nip.io --host-data-dir /Users/myusername/.oc/profiles/cicd2day/data --host-config-dir /Users/myusername/.oc/profiles/cicd2day/config --use-existing-config -e TZ=CEST
```

Or - step-by-step:

```
oc-cluster up _PROFILENAME_ --image="registry.access.redhat.com/openshift3/ose" --version=v3.4.1.10
oc login -u system:admin
oc project default
oc adm policy add-cluster-role-to-user cluster-admin developer
oc adm policy add-cluster-role-to-user cluster-admin admin

git clone https://github.com/OpenShiftDemos/openshift-cd-demo
cd openshift-cd-demo
Admin permissions as above!
oc login -u developer
oc new-project dev --display-name="Tasks - Dev"
oc new-project stage --display-name="Tasks - Stage"
oc new-project cicd --display-name="CI/CD"

oc policy add-role-to-user edit system:serviceaccount:cicd:default -n dev
oc policy add-role-to-user edit system:serviceaccount:cicd:default -n stage
oc policy add-role-to-user edit system:serviceaccount:cicd:default -n cicd
oc process -f cicd-template.yaml -v DEV_PROJECT=dev -v STAGE_PROJECT=stage | oc create -f - -n cicd
```

This finally brought the cicd project successfully up (with the exception of the install-gogs pod, see the separate issue at https://github.com/OpenShiftDemos/openshift-cd-demo/issues/45 ). I.e. all gogs, Nexus, SonarQube running and accessible.

What I did now was "migrating" the _openshift-tasks_ repository to the local gogs installation as install-gogs failed and there was no repository available.

Then I opened Jenkins, checked the pipeline script of the cicd/tasks-pipeline which was 

```
node('maven') {
             // define commands
             def mvnCmd = "mvn -s configuration/cicd-settings.xml"

             stage 'Build'
             git branch: 'eap-7', url: 'http://gogs:3000/gogs/openshift-tasks.git'
             def v = version()
             sh "${mvnCmd} clean install -DskipTests=true"

             stage 'Test and Analysis'
             parallel (
                 'Test': {
                     sh "${mvnCmd} test"
                     step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
                 },
                 'Static Analysis': {
                     sh "${mvnCmd} jacoco:report sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -DskipTests=true"
                 }
             )

             stage 'Push to Nexus'
             sh "${mvnCmd} deploy -DskipTests=true"

             stage 'Deploy DEV'
             sh "rm -rf oc-build && mkdir -p oc-build/deployments"
             sh "cp target/openshift-tasks.war oc-build/deployments/ROOT.war"
             // clean up. keep the image stream
             sh "oc project ${DEV_PROJECT}"
             sh "oc delete bc,dc,svc,route -l app=tasks -n ${DEV_PROJECT}"
             // create build. override the exit code since it complains about exising imagestream
             sh "oc new-build --name=tasks --image-stream=jboss-eap70-openshift --binary=true --labels=app=tasks -n ${DEV_PROJECT} || true"
             // build image
             sh "oc start-build tasks --from-dir=oc-build --wait=true -n ${DEV_PROJECT}"
             // deploy image
             sh "oc new-app tasks:latest -n ${DEV_PROJECT}"
             sh "oc expose svc/tasks -n ${DEV_PROJECT}"

             stage 'Deploy STAGE'
             input message: "Promote to STAGE?", ok: "Promote"
             sh "oc project ${STAGE_PROJECT}"
             // tag for stage
             sh "oc tag ${DEV_PROJECT}/tasks:latest ${STAGE_PROJECT}/tasks:${v}"
             // clean up. keep the imagestream
             sh "oc delete bc,dc,svc,route -l app=tasks -n ${STAGE_PROJECT}"
             // deploy stage image
             sh "oc new-app tasks:${v} -n ${STAGE_PROJECT}"
             sh "oc expose svc/tasks -n ${STAGE_PROJECT}"
          }

          def version() {
            def matcher = readFile('pom.xml') =~ '<version>(.+)</version>'
            matcher ? matcher[0][1] : null
          }
```

like in the template and didn't need further adjustments as shown in the video.

I ran the pipeline and it went up to the Nexus deployment successfully by deploying a _jboss-tasks-rs-7.0.0-20170404.142030-2.war_ artifact (amongst others).

Then the _Deploy DEV_ fails with:

```
[Pipeline] stage (Deploy DEV)
Using the ‘stage’ step without a block argument is deprecated
Entering stage Deploy DEV
Proceeding
[Pipeline] sh
[cicd-tasks-pipeline] Running shell script
+ rm -rf oc-build
+ mkdir -p oc-build/deployments
[Pipeline] sh
[cicd-tasks-pipeline] Running shell script
+ cp target/openshift-tasks.war oc-build/deployments/ROOT.war
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
groovy.lang.MissingPropertyException: No such property: DEV_PROJECT for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:224)
	at org.kohsuke.groovy.sandbox.impl.Checker$4.call(Checker.java:241)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:238)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:221)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:24)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at WorkflowScript.run(WorkflowScript:28)
	at ___cps.transform___(Native Method)
	at (...)
Finished: FAILURE
``` 

One observation: I assume the artifact for deployment is not taken from Nexus (as single source of truth) but from the local Jenkins dir to reduce demo complexity, right?

Now my question: what do I need to do to get DEV_PROJECT resolved? Seems that using it in the _oc process_ creation command is not sufficient?

Any troubleshooting advice?

Thanks and best wishes,

Karsten

**Comment by karstengresch** [comment]
Update: Edited the build config as a workaround by hardcoding the env var:

```
env.DEV_PROJECT = 'dev'
```

Now the internal _oc_ complains about missing access rights:

```
[Pipeline] stage (Deploy DEV)
Using the ‘stage’ step without a block argument is deprecated
Entering stage Deploy DEV
Proceeding
[Pipeline] sh
[cicd-tasks-pipeline] Running shell script
+ rm -rf oc-build
+ mkdir -p oc-build/deployments
[Pipeline] sh
[cicd-tasks-pipeline] Running shell script
+ cp target/openshift-tasks.war oc-build/deployments/ROOT.war
[Pipeline] sh
[cicd-tasks-pipeline] Running shell script
+ oc project dev
error: You are not a member of project "dev".
You have one project on this server: CI/CD (cicd)
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by karstengresch** [comment]
Ok, as a workaround from the dark side of the force I could get it running:

```
oc adm policy add-role-to-user admin system:serviceaccount:cicd:jenkins -n stage
oc adm policy add-role-to-user admin system:serviceaccount:cicd:jenkins -n dev
```

For my purposes it's ok.
